### ISSUE TITLE
bug with tokenize

### ISSUE THREAD

**Issue by WilliamMaber** [thunlp/Few-NERD#16]
output. i an not sure what is worng
```
Traceback (most recent call last):
  File "/home/william/Few-NERD/train_demo.py", line 183, in <module>
    main()
  File "/home/william/Few-NERD/train_demo.py", line 149, in main
    framework = FewShotNERFramework(train_data_loader, val_data_loader, test_data_loader, N=opt.N, tau=opt.tau, train_fname=opt.train, viterbi=True, use_sampled_data=opt.use_sampled_data)
  File "/home/william/Few-NERD/util/framework.py", line 299, in __init__
    abstract_transitions = get_abstract_transitions(train_fname, use_sampled_data=use_sampled_data)
  File "/home/william/Few-NERD/util/framework.py", line 30, in get_abstract_transitions
    tag_lists = [sample.tags for sample in samples]
  File "/home/william/Few-NERD/util/framework.py", line 30, in <listcomp>
    tag_lists = [sample.tags for sample in samples]
  File "/home/william/Few-NERD/util/data_loader.py", line 203, in __getitem__
    support_set = self.__populate__(support_idx)
  File "/home/william/Few-NERD/util/data_loader.py", line 186, in __populate__
    tokens, labels = self.__get_token_label_list__(self.samples[idx])
  File "/home/william/Few-NERD/util/data_loader.py", line 114, in __get_token_label_list__
    word_tokens = self.tokenizer.tokenize(word)
AttributeError: 'NoneType' object has no attribute 'tokenize'
```

**Comment by cyl628** [comment]
thanks for reporting, we have fixed the bug
